### ISSUE TITLE
Uncaught InvalidArgumentException: Authentication user provider [encryptedUserProvider] is not defin...

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#978]
**`Symfony\Component\ErrorHandler\Error\FatalError`**

Uncaught InvalidArgumentException: Authentication user provider [encryptedUserProvider] is not defined. in /app/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php:39
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(121): Illuminate\Auth\AuthManager->createUserProvider('users')
#1 /app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(92): Illuminate\Auth\AuthManager->createSessionDriver('web', Array)
#2 /app/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(66): Illuminate\Auth\AuthManager->resolve('web')
#3 /opt/data/storage/framework/views/f5e5ab3550c672e6f666fcc2461ab6593e4ab5ff.php(15): Illuminate\Auth\AuthManager->guard()
#4 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/opt/data/stora...')
#5 /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#6 /app/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/opt/data/stora...', Array)
#7 /app/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/data/stora...', Array)
#8 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\LivewireViewCompilerEngine->evaluatePath('/opt/data/stora...', Array)
#9 /app/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\View\Engines\CompilerEngine->get('/app/resources/...', Array)
#10 /app/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\LivewireViewCompilerEngine->get('/app/resources/...', Array)
#11 /app/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\View\View->getContents()
#12 /app/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#13 /opt/data/storage/framework/views/695e65b3db1ccf0f33e9fd60b44727b79b0cd896.php

:dart: /app/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php
:page_facing_up: /app/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php

[Open in Flare](https://flareapp.io/errors/1509945/latest)

**Comment by greatislander** [comment]
Appears to be resolved.
